"""
Confluence wiki storage HTML export for migration plans.
"""

from __future__ import annotations

import html

from ama.export.config import ExportConfig
from ama.export.md_inline import md_inline_to_html
from ama.planner.models import MigrationPlan, PlannedTable


def _plan_title_focus(plan: MigrationPlan) -> str:
    """Human-readable plan focus line (uses migration context when set)."""
    ctx = (plan.migration_context or "").strip()
    return ctx if ctx else "Migration"


def _truncate_note_cell(text: str, max_len: int = 200) -> str:
    """Truncate note column text with an ellipsis suffix."""
    t = text.strip()
    if len(t) <= max_len:
        return t
    return t[: max_len - 1] + "…"


def _row_note(pt: PlannedTable) -> str:
    """Prefer technical_note, else business_context (Markdown ** / ` → HTML)."""
    tn = (pt.technical_note or "").strip()
    raw = tn if tn else (pt.business_context or "").strip()
    return md_inline_to_html(_truncate_note_cell(raw))


class ConfluenceExportSink:
    """Renders a :class:`MigrationPlan` as Confluence wiki storage HTML."""

    def write(self, plan: MigrationPlan, config: ExportConfig) -> str:
        """Return one HTML document string."""
        _ = config  # reserved for future format-specific options
        wave_count = len(plan.waves)
        parts: list[str] = []
        title = html.escape(_plan_title_focus(plan))
        ver = html.escape(str(plan.version))
        parts.append(f"<h1>Migration Plan: {title}</h1>")
        parts.append(
            "<p><em>Generated by AMA · ama.planner v"
            f"{ver} · {wave_count} waves</em></p>"
        )

        for wave in plan.waves:
            wname = html.escape(wave.name)
            parts.append(f"<h2>Wave {wave.wave_id}: {wname}</h2>")
            br_raw = wave.business_rationale or ""
            dm_imp = wave.metrics.get("domain_matrix_importance")
            if dm_imp is not None:
                try:
                    v = float(dm_imp)
                    br_raw = f"{br_raw} (domain importance: {v}%)"
                except (TypeError, ValueError):
                    pass
            br = md_inline_to_html(br_raw)
            parts.append(f"<p><strong>Business rationale:</strong> {br}</p>")
            tr = md_inline_to_html(wave.technical_rationale or "")
            parts.append(f"<p><strong>Technical rationale:</strong> {tr}</p>")
            parts.append(
                "<table>"
                "<tr><th>Table</th><th>Domain</th><th>Priority</th>"
                "<th>Queries</th><th>Note</th></tr>"
            )
            for t in wave.tables:
                fn = html.escape(t.full_name)
                dom = html.escape(t.business_domain)
                pri = html.escape(f"{t.priority_score:.1f}%")
                qc = html.escape(str(t.query_count))
                note = _row_note(t)
                parts.append(
                    "<tr>"
                    f"<td><code>{fn}</code></td>"
                    f"<td>{dom}</td>"
                    f"<td>{pri}</td>"
                    f"<td>{qc}</td>"
                    f"<td>{note}</td>"
                    "</tr>"
                )
            parts.append("</table>")

        for note in plan.notes:
            ne = md_inline_to_html(note)
            parts.append(
                '<ac:structured-macro ac:name="info">'
                "<ac:rich-text-body>"
                f"<p>{ne}</p>"
                "</ac:rich-text-body>"
                "</ac:structured-macro>"
            )

        return "".join(parts)
