from __future__ import annotations

import csv
import hashlib
import json
import logging
import re
from pathlib import Path
from typing import Any, Callable

from ama.ai_query_helper import (
    OpenAIAuthError,
    OpenAIQueryError,
    OpenAIRateLimitError,
    query_openai_json,
)
from ama.dbt_migration.agent_prompts import get_agent_prompt
from ama.dbt_migration.mapping import apply_semantic_translation_for_unresolved, build_mapping_row
from ama.dbt_migration.models import (
    BrokenLineageStub,
    MappingRow,
    MappingSource,
    ModelArtifact,
    ModelMetadata,
    TargetDialect,
)
from ama.dbt_migration.sql_transpile import transpile_sql
from ama.dbt_migration.sql_self_heal import run_sql_self_healing_loop
from ama.env_resolver import has_openai_api_key

logger = logging.getLogger(__name__)


def _sanitize_model_name(table_key: str) -> str:
    return "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in table_key.lower())


def _schema_yml_for_model(model_name: str) -> str:
    return (
        "version: 2\n\n"
        "models:\n"
        f"  - name: {model_name}\n"
        "    description: Generated by AMA agentic extension\n"
        "    columns: []\n"
    )


def _build_normal_model_sql(
    table_key: str,
    mapped_columns: list[MappingRow],
    target_dialect: TargetDialect,
) -> str:
    if mapped_columns:
        projection = ",\n  ".join(
            f'"{row.hebrew_name}" AS {row.english_alias}' for row in mapped_columns
        )
    else:
        projection = "*"
    canonical_select = (
        "SELECT\n"
        f"  {projection}\n"
        f"FROM \"{table_key}\""
    )
    transpiled = transpile_sql(canonical_select, target_dialect)
    return "{{ config(materialized='view') }}\n\n" + transpiled


def _looks_like_select_sql(sql: str) -> bool:
    text = (sql or "").strip().lower()
    return "select" in text and "from" in text


def _contains_hebrew(value: str) -> bool:
    """Quick check for Hebrew codepoints used for deterministic translation rationale."""
    if not value:
        return False
    return bool(re.search(r"[\u0590-\u05FF]", value))


def _call_schema_agent(
    *,
    table_key: str,
    source_ddl_columns: list[str],
    raw_columns: list[str],
    ama_rationale: str,
) -> tuple[dict[str, Any], int, float]:
    user_prompt = json.dumps(
        {
            "table_key": table_key,
            "source_ddl_columns": source_ddl_columns,
            "sample_data_columns": raw_columns,
            "ama_report_rationale": ama_rationale,
            "response_schema": {
                "context_analysis": "string",
                "suggested_columns": ["string"],
                "confidence": "float_0_to_1",
            },
        },
        ensure_ascii=False,
    )
    result = query_openai_json(
        system_prompt=get_agent_prompt("schema_agent"),
        user_prompt=user_prompt,
        max_tokens=1200,
        timeout_seconds=45,
        temperature=0.0,
    )
    payload = result.payload
    confidence = float(payload.get("confidence") or 0.0)
    return payload, result.tokens_used, confidence


def _call_dbt_agent(
    *,
    table_key: str,
    schema_agent_output: dict[str, Any],
    mapped_columns: list[MappingRow],
    business_rationale: str,
    target_dialect: TargetDialect,
) -> tuple[str, str, int, float]:
    system_prompt = get_agent_prompt("dbt_agent").replace("{TARGET_DIALECT}", target_dialect.value)
    user_prompt = json.dumps(
        {
            "table_key": table_key,
            "schema_agent_output": schema_agent_output,
            "mapped_columns": [{"old": row.hebrew_name, "new": row.english_alias} for row in mapped_columns],
            "business_rationale": business_rationale,
            "target_dialect": target_dialect.value,
            "response_schema": {"sql": "string", "reasoning": "string", "confidence": "float_0_to_1"},
        },
        ensure_ascii=False,
    )
    result = query_openai_json(
        system_prompt=system_prompt,
        user_prompt=user_prompt,
        max_tokens=2500,
        timeout_seconds=60,
        temperature=0.1,
    )
    payload = result.payload
    sql = str(payload.get("sql") or "")
    reasoning = str(payload.get("reasoning") or "")
    confidence = float(payload.get("confidence") or 0.0)
    return sql, reasoning, result.tokens_used, confidence


def build_stub_model(
    table_key: str,
    rationale: str,
    identified_columns: list[str],
) -> BrokenLineageStub:
    return BrokenLineageStub(
        table_key=table_key,
        business_rationale=rationale,
        identified_columns=identified_columns,
    )


def _extract_manifest_columns(node: dict[str, Any]) -> list[str]:
    columns = node.get("columns")
    if not isinstance(columns, dict):
        return []
    return [str(k) for k in columns.keys()]


def _extract_unique_key(node: dict[str, Any]) -> str | list[str] | None:
    cfg = node.get("config")
    if isinstance(cfg, dict) and "unique_key" in cfg:
        return cfg.get("unique_key")
    return None


def load_models_from_manifest(manifest_path: Path) -> list[ModelMetadata]:
    try:
        raw = manifest_path.read_text(encoding="utf-8")
        payload = json.loads(raw)
    except OSError as exc:
        raise ValueError(f"failed to read manifest file: {manifest_path}") from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid manifest JSON: {manifest_path}") from exc
    nodes = payload.get("nodes")
    if not isinstance(nodes, dict):
        return []
    out: list[ModelMetadata] = []
    for node_id in sorted(nodes.keys()):
        node = nodes[node_id]
        if not isinstance(node, dict):
            continue
        if str(node.get("resource_type", "")).lower() != "model":
            continue
        model_name = str(node.get("name") or "")
        if not model_name:
            continue
        schema = str(node.get("schema") or "")
        alias = str(node.get("alias") or model_name)
        relation = f"{schema}.{alias}" if schema else alias
        materialized = "view"
        cfg = node.get("config")
        if isinstance(cfg, dict):
            materialized = str(cfg.get("materialized") or "view")
        out.append(
            ModelMetadata(
                model_name=model_name,
                relation_name=relation,
                materialized=materialized,
                ddl_columns=_extract_manifest_columns(node),
                unique_key=_extract_unique_key(node),
                model_path=str(node.get("original_file_path") or ""),
                config=cfg if isinstance(cfg, dict) else {},
            )
        )
    return out


def load_usage_csv(usage_csv_path: Path) -> dict[str, dict[str, int]]:
    usage: dict[str, dict[str, int]] = {}
    try:
        with usage_csv_path.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            for row in reader:
                model = str((row or {}).get("model_name") or "").strip()
                column = str((row or {}).get("column_name") or "").strip()
                usage_count_raw = str((row or {}).get("usage_count") or "0").strip()
                if not model or not column:
                    continue
                try:
                    usage_count = int(usage_count_raw)
                except ValueError:
                    usage_count = 0
                usage.setdefault(model, {})
                usage[model][column] = usage[model].get(column, 0) + usage_count
    except OSError as exc:
        raise ValueError(f"failed to read usage CSV file: {usage_csv_path}") from exc
    return usage


def select_columns_for_model(metadata: ModelMetadata, usage_by_model: dict[str, dict[str, int]]) -> list[str]:
    usage_cols = usage_by_model.get(metadata.model_name, {})
    valid_usage = []
    ddl_lookup = {c.lower(): c for c in metadata.ddl_columns}
    for used_col in sorted(usage_cols.keys()):
        if used_col.lower() in ddl_lookup:
            valid_usage.append(ddl_lookup[used_col.lower()])
        else:
            logger.warning(
                "usage_column_missing_from_ddl",
                extra={"model_name": metadata.model_name, "column_name": used_col},
            )
    metadata.usage_columns = valid_usage
    # Per requirement: include all DDL columns by default.
    metadata.selected_columns = list(metadata.ddl_columns)
    return metadata.selected_columns


def validate_incremental_unique_key(metadata: ModelMetadata) -> None:
    if metadata.materialized != "incremental":
        return
    uk = metadata.unique_key
    if uk is None:
        raise ValueError(f"incremental model '{metadata.model_name}' missing unique_key")
    if isinstance(uk, str) and not uk.strip():
        raise ValueError(f"incremental model '{metadata.model_name}' has empty unique_key")
    if isinstance(uk, list) and not [x for x in uk if str(x).strip()]:
        raise ValueError(f"incremental model '{metadata.model_name}' has empty unique_key list")


def _infer_incremental_ordering_field_and_strategy(columns: list[str]) -> tuple[str, str]:
    """
    Heuristic for choosing an incremental ordering field:
    - Prefer event-time columns (event/occurred + time/timestamp/_at).
    - Otherwise use file/ingestion-time columns (file/ingest/source + time/timestamp/_at).
    - Fallback to the first timestamp-like column, else the first column.
    """
    cols = [str(c).strip() for c in (columns or []) if str(c).strip()]
    if not cols:
        return "id", "file-time"

    time_like = [c for c in cols if re.search(r"(time|timestamp|_at|_ts|_dt)", c.lower())]
    if not time_like:
        return cols[0], "file-time"

    def _has_any(s: str, needles: list[str]) -> bool:
        s_l = s.lower()
        return any(n in s_l for n in needles)

    event_time_cols = [
        c
        for c in time_like
        if _has_any(c, ["event", "occur", "occurred", "processing_time", "processed_at"])
    ]
    if event_time_cols:
        return event_time_cols[0], "event-time"

    file_time_cols = [
        c
        for c in time_like
        if _has_any(c, ["file", "ingest", "ingestion", "source", "loaded", "load_at", "received"])
    ]
    if file_time_cols:
        return file_time_cols[0], "file-time"

    return time_like[0], "file-time"


def render_canonical_sql(metadata: ModelMetadata, target_dialect: TargetDialect) -> str:
    projection = ",\n  ".join(f'"{col}" AS {col.lower()}' for col in metadata.selected_columns) or "*"
    canonical_select = f'SELECT\n  {projection}\nFROM "{metadata.relation_name}"'
    transpiled = transpile_sql(canonical_select, target_dialect)
    config_materialized = "{{ config(materialized='" + metadata.materialized + "') }}\n\n"

    if metadata.materialized != "incremental":
        return config_materialized + transpiled + "\n"

    # For incremental models, dbt typically requires `unique_key`.
    uk = metadata.unique_key
    if isinstance(uk, list):
        # Jinja can pass lists; represent it in a stable way.
        uk_expr = "[" + ", ".join(f"'{str(x)}'" for x in uk if str(x).strip()) + "]"
    else:
        uk_expr = "'" + str(uk).strip() + "'"

    ordering_field, ordering_strategy = _infer_incremental_ordering_field_and_strategy(metadata.ddl_columns)
    ordering_predicate = (
        f'WHERE "{ordering_field}" > (\n'
        f"  SELECT COALESCE(MAX(\"{ordering_field}\"), CAST('1900-01-01' AS TIMESTAMP))\n"
        f"  FROM {{{{ this }}}}\n"
        f")"
    )

    # Keep ordering metadata as plain comments for transparency.
    ordering_comments = (
        f"-- incremental_ordering_strategy: {ordering_strategy}\n"
        f"-- incremental_ordering_field: {ordering_field}\n"
    )
    return (
        "{{ config(materialized='incremental', unique_key=" + uk_expr + ") }}\n\n"
        + transpiled
        + "\n\n"
        + ordering_comments
        + "{% if is_incremental() %}\n"
        + ordering_predicate
        + "\n{% endif %}\n"
    )


def upsert_sql_if_changed(sql_path: Path, sql_content: str) -> bool:
    try:
        sql_path.parent.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise ValueError(f"failed to create output directory: {sql_path.parent}") from exc
    new_hash = hashlib.sha256(sql_content.encode("utf-8")).hexdigest()
    if sql_path.is_file():
        try:
            old_hash = hashlib.sha256(sql_path.read_text(encoding="utf-8").encode("utf-8")).hexdigest()
        except OSError as exc:
            raise ValueError(f"failed to read existing SQL file: {sql_path}") from exc
        if old_hash == new_hash:
            return False
    try:
        sql_path.write_text(sql_content, encoding="utf-8")
    except OSError as exc:
        raise ValueError(f"failed to write SQL file: {sql_path}") from exc
    return True


def generate_models_from_manifest(
    *,
    manifest_path: Path,
    usage_csv_path: Path,
    output_dir: Path,
    target_dialect: TargetDialect,
) -> list[ModelMetadata]:
    models = load_models_from_manifest(manifest_path)
    usage = load_usage_csv(usage_csv_path)
    for metadata in models:
        select_columns_for_model(metadata, usage)
        validate_incremental_unique_key(metadata)
        sql = render_canonical_sql(metadata, target_dialect)
        sql_file = output_dir / f"{metadata.model_name}.sql"
        changed = upsert_sql_if_changed(sql_file, sql)
        logger.info(
            "model_sql_generated",
            extra={
                "model_name": metadata.model_name,
                "sql_path": str(sql_file),
                "changed": changed,
                "column_count": len(metadata.selected_columns),
            },
        )
    return models


def stub_sql_from_broken_lineage(stub: BrokenLineageStub) -> str:
    cols = ", ".join(stub.identified_columns) if stub.identified_columns else "none identified"
    return (
        "-- WARNING: UNRESOLVED BROKEN LINEAGE\n"
        f"-- Business rationale: {stub.business_rationale or 'Missing from DDL manifest'}\n"
        f"-- Identified columns: {cols}\n"
        "select\n"
        "  null as unresolved_broken_lineage\n"
        "where 1=0\n"
    )


def generate_model_artifact(
    table_key: str,
    raw_columns: list[str],
    glossary: dict[str, str],
    alias_registry: dict[str, str],
    target_dialect: TargetDialect,
    source_ddl_columns: list[str] | None = None,
    *,
    broken: bool,
    rationale: str,
    thought_callback: Callable[[str, dict[str, Any]], None] | None = None,
    max_correction_attempts: int = 3,
) -> tuple[ModelArtifact, list[MappingRow]]:
    model_name = _sanitize_model_name(table_key)
    ai_telemetry: list[dict[str, Any]] = []
    generation_mode = "legacy"
    fallback_reason = ""
    auth_error = False
    rate_limit_error = False
    raw_preview = ", ".join([str(c) for c in raw_columns[:8]]) if raw_columns else "—"
    schema_reasoning = (
        f"Schema agent not executed (LLM disabled/unavailable) for `{table_key}`. "
        f"Deterministic column inventory drives the projection and review flags (n={len(raw_columns)}): {raw_preview}."
    )
    dbt_reasoning = (
        f"dbt agent not executed (LLM disabled/unavailable) for `{table_key}`. "
        f"Using deterministic SQL: `SELECT` projection from source plus transpilation to `{target_dialect.value}`."
    )
    generation_confidence = 0.0

    # Always expose full DDL column inventory in Checkpoint A mapping.
    # `raw_columns` are what we observed in the logs; `source_ddl_columns` are the full
    # manifest/DDL set for the table.
    source_ddl_columns = source_ddl_columns or []
    raw_set = {str(c) for c in (raw_columns or [])}
    extra_from_ddl = [str(c) for c in source_ddl_columns if str(c) not in raw_set]
    ddl_only_cols = set(extra_from_ddl)
    all_columns = list(dict.fromkeys(list(raw_columns or []) + extra_from_ddl))

    if thought_callback is not None:
        thought_callback(
            "THOUGHT",
            {
                "agent_role": "Architect",
                "message": f"Mapping Hebrew/DDL columns (total={len(all_columns)}).",
                "table_key": table_key,
            },
        )

    mapped = [build_mapping_row(col, glossary, alias_registry) for col in all_columns]

    # Snapshot inputs for semantic-mapping rationale.
    initial_source_by_col = {row.hebrew_name: row.source.value for row in mapped}
    unresolved_hebrew_cols = [
        row.hebrew_name
        for row in mapped
        if row.source == MappingSource.TRANSLITERATION and _contains_hebrew(row.hebrew_name)
    ]

    if thought_callback is not None and unresolved_hebrew_cols:
        thought_callback(
            "THOUGHT",
            {
                "agent_role": "Architect",
                "message": f"Semantic translation for unresolved Hebrew columns (n={len(unresolved_hebrew_cols)}).",
                "table_key": table_key,
            },
        )
    try:
        mapped, translation_meta = apply_semantic_translation_for_unresolved(
            mapped_rows=mapped,
            glossary=glossary,
            model_business_logic=rationale,
            alias_registry=alias_registry,
        )
    except OpenAIAuthError:
        auth_error = True
        raise
    ai_telemetry.append({"agent_name": "translation_agent", **translation_meta})
    if thought_callback is not None:
        thought_callback(
            "THOUGHT",
            {
                "agent_role": "Architect",
                "message": "Completed Hebrew-to-English mapping stage.",
                "table_key": table_key,
                "confidence": float(translation_meta.get("confidence") or 0.0),
            },
        )
    low_confidence_translation = float(translation_meta.get("confidence") or 0.0) < 0.8
    review_required = broken or low_confidence_translation or any(
        "[TRANSLITERATION_WARNING]" in (m.warning_flags or []) for m in mapped
    )

    # Mark columns that came only from the DDL (not observed in logs) for operator clarity.
    if ddl_only_cols:
        for r in mapped:
            if r.hebrew_name in ddl_only_cols and "[DDL_ONLY_WARNING]" not in (r.warning_flags or []):
                r.warning_flags.append("[DDL_ONLY_WARNING]")

    translation_rationale = ""
    mapping_decision_tag = "HUMAN_REQUIRED"
    translated_cols: list[str] = []
    residual_transliteration_cols: list[str] = []
    mapped_by_name = {r.hebrew_name: r for r in mapped}
    if not unresolved_hebrew_cols:
        translation_rationale = "No unresolved Hebrew column names detected; used glossary and transliteration as provided."
        mapping_decision_tag = "AI_AUTONOMOUS"
    else:
        for c in unresolved_hebrew_cols:
            after = mapped_by_name.get(c)
            if after is None:
                continue
            before_src = initial_source_by_col.get(c)
            if before_src == MappingSource.TRANSLITERATION.value and after.source != MappingSource.TRANSLITERATION:
                translated_cols.append(c)
            if after.source == MappingSource.TRANSLITERATION:
                residual_transliteration_cols.append(c)

        batch_conf = float(translation_meta.get("confidence") or 0.0)
        fallback = bool(translation_meta.get("is_fallback_active") or False)
        tokens_used = int(translation_meta.get("tokens_used") or 0)

        if fallback or tokens_used == 0:
            translation_rationale = (
                f"Semantic translation skipped (LLM fallback/unavailable) for {len(unresolved_hebrew_cols)} column(s). "
                "Kept transliteration for those names."
            )
        else:
            examples = ", ".join(translated_cols[:6]) if translated_cols else "none"
            translation_rationale = (
                f"Semantic translation applied for {len(translated_cols)}/{len(unresolved_hebrew_cols)} column(s) "
                f"(batch confidence={batch_conf:.2f}). Translated examples: {examples}."
            )

        if residual_transliteration_cols:
            translation_rationale += f" [TRANSLITERATION_WARNING] still needed for: {', '.join(residual_transliteration_cols[:6])}."

        if not fallback and batch_conf >= 0.8 and not residual_transliteration_cols:
            mapping_decision_tag = "AI_AUTONOMOUS"
        else:
            mapping_decision_tag = "HUMAN_REQUIRED"

    if thought_callback is not None:
        thought_callback(
            "THOUGHT",
            {
                "agent_role": "Developer",
                "message": f"Draft dbt SQL for target dialect '{target_dialect.value}' (broken={broken}).",
                "table_key": table_key,
            },
        )

    if broken:
        stub = build_stub_model(table_key, rationale, [m.english_alias for m in mapped])
        sql = stub_sql_from_broken_lineage(stub)
        generation_mode = "legacy"
        schema_reasoning = (
            f"Broken lineage detected for `{table_key}`. Schema agent reasoning is unavailable; generating an unresolved stub SQL "
            f"to keep the migration pipeline moving (rationale: {rationale[:160]})."
        )
        dbt_reasoning = (
            f"Using broken-lineage stub SQL (no LLM) for `{table_key}`. Projection is intentionally disabled to avoid incorrect casts/columns."
        )
    else:
        sql = _build_normal_model_sql(table_key, mapped, target_dialect)
        if has_openai_api_key():
            try:
                if thought_callback is not None:
                    thought_callback(
                        "THOUGHT",
                        {
                            "agent_role": "Developer",
                            "message": "Calling schema_agent to refine context.",
                            "table_key": table_key,
                        },
                    )
                schema_payload, schema_tokens, schema_conf = _call_schema_agent(
                    table_key=table_key,
                    source_ddl_columns=source_ddl_columns or [],
                    raw_columns=raw_columns,
                    ama_rationale=rationale,
                )
                logger.info(
                    "llm_agent_telemetry",
                    extra={
                        "agent_name": "schema_agent",
                        "tokens_used": schema_tokens,
                        "confidence": round(schema_conf, 4),
                        "is_fallback_active": False,
                    },
                )
                schema_reasoning = str(schema_payload.get("context_analysis") or "").strip()
                if not schema_reasoning:
                    suggested = schema_payload.get("suggested_columns")
                    suggested_txt = ""
                    if isinstance(suggested, list) and suggested:
                        suggested_txt = ", ".join(str(x) for x in suggested[:8])
                    schema_reasoning = (
                        "Schema agent returned no `context_analysis`; falling back to deterministic interpretation. "
                        + (f"Suggested columns: {suggested_txt}." if suggested_txt else "Using mapped column inventory.")
                    )
                ai_telemetry.append(
                    {
                        "agent_name": "schema_agent",
                        "tokens_used": schema_tokens,
                        "confidence": round(schema_conf, 4),
                        "is_fallback_active": False,
                    }
                )
                if thought_callback is not None:
                    thought_callback(
                        "THOUGHT",
                        {
                            "agent_role": "Developer",
                            "message": "Calling dbt_agent to draft SQL.",
                            "table_key": table_key,
                        },
                    )
                llm_sql, dbt_reasoning, dbt_tokens, dbt_conf = _call_dbt_agent(
                    table_key=table_key,
                    schema_agent_output=schema_payload,
                    mapped_columns=mapped,
                    business_rationale=rationale,
                    target_dialect=target_dialect,
                )
                logger.info(
                    "llm_agent_telemetry",
                    extra={
                        "agent_name": "dbt_agent",
                        "tokens_used": dbt_tokens,
                        "confidence": round(dbt_conf, 4),
                        "is_fallback_active": False,
                    },
                )
                dbt_reasoning = str(dbt_reasoning or "").strip()
                if not dbt_reasoning:
                    dbt_reasoning = (
                        "dbt agent returned no `reasoning`; generated SQL using deterministic projection "
                        f"({len(mapped)} mapped columns) and dialect transpilation."
                    )
                ai_telemetry.append(
                    {
                        "agent_name": "dbt_agent",
                        "tokens_used": dbt_tokens,
                        "confidence": round(dbt_conf, 4),
                        "is_fallback_active": False,
                    }
                )
                if _looks_like_select_sql(llm_sql):
                    sql = llm_sql
                    generation_mode = "ai"
                    generation_confidence = float(dbt_conf)
                else:
                    fallback_reason = "dbt_agent_invalid_sql"
                    logger.warning(
                        "llm_agent_fallback",
                        extra={
                            "agent_name": "dbt_agent",
                            "tokens_used": dbt_tokens,
                            "confidence": round(dbt_conf, 4),
                            "is_fallback_active": True,
                        },
                    )
            except OpenAIAuthError:
                auth_error = True
                raise
            except OpenAIRateLimitError as exc:
                rate_limit_error = True
                fallback_reason = "rate_limit"
                msg = str(exc).strip()
                msg_short = (msg[:180] + "...") if len(msg) > 180 else msg
                schema_reasoning = (
                    f"LLM rate-limited while generating schema context for `{table_key}`: {msg_short or '429'}. "
                    "Falling back to deterministic schema interpretation for this model."
                )
                dbt_reasoning = (
                    f"LLM rate-limited while generating dbt SQL for `{table_key}`. "
                    "Falling back to deterministic SQL projection + dialect transpilation."
                )
                logger.warning(
                    "llm_agent_fallback",
                    extra={
                        "agent_name": "generation_agents",
                        "tokens_used": 0,
                        "confidence": 0.0,
                        "is_fallback_active": True,
                    },
                )
            except (OpenAIQueryError, ValueError, TypeError) as exc:
                fallback_reason = "llm_error"
                msg = str(exc).strip()
                msg_short = (msg[:180] + "...") if len(msg) > 180 else msg
                schema_reasoning = (
                    f"LLM error while generating schema context for `{table_key}`: {msg_short or exc.__class__.__name__}. "
                    f"Falling back to deterministic interpretation (n={len(raw_columns)}): {raw_preview}."
                )
                dbt_reasoning = (
                    f"LLM error while generating dbt SQL for `{table_key}`: {msg_short or exc.__class__.__name__}. "
                    f"Falling back to deterministic SQL projection + transpilation to `{target_dialect.value}`."
                )
                logger.warning(
                    "llm_agent_fallback",
                    extra={
                        "agent_name": "generation_agents",
                        "tokens_used": 0,
                        "confidence": 0.0,
                        "is_fallback_active": True,
                    },
                )

    # QA Lead: validate SQL with sqlglot, then bounded self-healing if rejected.
    fallback_sql = sql
    if not broken:
        # Deterministic fallback that bypasses LLM variability.
        fallback_sql = _build_normal_model_sql(table_key, mapped, target_dialect)

    def _developer_self_correct_sql(
        failed_sql: str,
        error_reasons: list[str],
        correction_attempt: int,
        _target_dialect: TargetDialect,
    ) -> str:
        nonlocal fallback_reason, auth_error, rate_limit_error
        if thought_callback is not None:
            thought_callback(
                "THOUGHT",
                {
                    "agent_role": "Developer",
                    "message": f"Self-correction call (attempt {correction_attempt}/{max_correction_attempts}).",
                    "table_key": table_key,
                    "correction_attempt": correction_attempt,
                    "reasons": error_reasons[:3],
                },
            )

        if not has_openai_api_key():
            return fallback_sql

        user_prompt = json.dumps(
            {
                "table_key": table_key,
                "model_name": model_name,
                "target_dialect": target_dialect.value,
                "failed_sql": failed_sql,
                "error_reasons": error_reasons,
                "correction_attempt": correction_attempt,
                "response_schema": {
                    "corrected_sql": "string",
                    "error_analysis": "string",
                    "confidence": "float_0_to_1",
                },
            },
            ensure_ascii=False,
        )
        try:
            result = query_openai_json(
                system_prompt=get_agent_prompt("developer_self_correct_agent"),
                user_prompt=user_prompt,
                max_tokens=2200,
                timeout_seconds=45,
                temperature=0.0,
            )
            payload = result.payload if isinstance(result.payload, dict) else {}
            corrected_sql = str(payload.get("corrected_sql") or "").strip()
            if corrected_sql and _looks_like_select_sql(corrected_sql):
                return corrected_sql
            fallback_reason = "self_correct_agent_invalid_sql"
            logger.warning(
                "self_correct_agent_invalid_sql",
                extra={
                    "agent_name": "developer_self_correct_agent",
                    "correction_attempt": correction_attempt,
                    "fallback_reason": fallback_reason,
                },
            )
        except OpenAIAuthError:
            auth_error = True
        except OpenAIRateLimitError:
            rate_limit_error = True
            fallback_reason = "self_correct_rate_limit"
        except (OpenAIQueryError, ValueError, TypeError):
            fallback_reason = "self_correct_llm_error"
        return fallback_sql

    final_sql, final_reasons, attempts, hitl_required = run_sql_self_healing_loop(
        initial_sql=sql,
        target_dialect=target_dialect,
        max_correction_attempts=max_correction_attempts,
        self_correct_sql=_developer_self_correct_sql,
        thought_callback=thought_callback,
    )
    sql = final_sql
    review_required = bool(review_required) or bool(hitl_required)
    self_heal_attempts_payload = [a.to_payload() for a in attempts]
    qa_error_reasons = list(final_reasons or []) if hitl_required else []
    critical_reason = ""
    if hitl_required:
        reasons_block = "\n".join(f"- {r}" for r in qa_error_reasons[:8])
        critical_reason = (
            "CRITICAL_REASON\n"
            f"table_key={table_key}\n"
            f"model_name={model_name}\n"
            f"target_dialect={target_dialect.value}\n"
            f"self_heal_max_attempts={max_correction_attempts}\n"
            "sql_rejection_reasons=\n"
            f"{reasons_block or '- none'}\n"
        )

    artifact = ModelArtifact(
        table_key=table_key,
        model_name=model_name,
        sql=sql,
        schema_yml=_schema_yml_for_model(model_name),
        mapping_rows=mapped,
        generation_mode=generation_mode,
        generation_confidence=generation_confidence,
        schema_agent_reasoning=schema_reasoning,
        dbt_agent_reasoning=dbt_reasoning,
        ai_telemetry=ai_telemetry,
        fallback_reason=fallback_reason,
        auth_error=auth_error,
        rate_limit_error=rate_limit_error,
        review_required=review_required,
        is_stub=broken,
        critical_reason=critical_reason,
        qa_error_reasons=qa_error_reasons,
        self_heal_attempts=self_heal_attempts_payload,
        translation_rationale=translation_rationale,
        mapping_decision_tag=mapping_decision_tag,
    )
    return artifact, mapped
